
FROM eclipse-temurin:21-jdk-jammy AS build


WORKDIR /app


COPY pom.xml .


RUN mvn dependency:go-offline -B


COPY src ./src


RUN mvn clean package -DskipTests


FROM eclipse-temurin:17-jre-alpine


WORKDIR /app


COPY --from=build /app/target/*.jar app.jar


EXPOSE 8080


ENV JWT_SECRET_KEY="sua_chave_secreta_padrao_para_deploy"


ENTRYPOINT ["java", "-jar", "app.jar"]